spring:
  application:
    name: zuul

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

server:
  port: 9095
zuul:
  routes:
    consume:
      path: /consume/**
      service-id: service-consume
    ribbon:
      path: /ribbon/**
      service-id: service-ribbon
    feign:
      path: /feign/**
      service-id: service-feign